import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import { GlobalFilterBar } from "@/components/GlobalFilterBar";
import { FilterProvider } from "@/contexts/FilterContext";

const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${urbanist.className} antialiased`}>
        <FilterProvider>
          <div className="min-h-screen bg-[color:var(--page-bg)] bg-blobs">
            <div className="mx-auto px-18 py-12">
              <GlobalFilterBar />
            </div>
            {children}
          </div>
        </FilterProvider>
      </body>
    </html>
  );
}
